import pandas as pd
import json
import os
import sys
import numpy as np
from datetime import datetime

# Force UTF-8
try:
    sys.stdout.reconfigure(encoding='utf-8')
except AttributeError:
    pass

HISTORY_FILE = "dice_history.csv"
SKILLS_FILE = "ai_skills.json"
MEMORY_FILE = "MARKET_MEMORY.md"

def analyze_and_learn():
    print("🧠 [Hermes AI Brain] Initiating Deep Learning Loop...")
    
    if not os.path.exists(HISTORY_FILE):
        print(f"❌ Error: {HISTORY_FILE} not found.")
        return

    try:
        df = pd.read_csv(HISTORY_FILE, header=None, names=[
            'timestamp', 'mode', 'step', 'bet', 'target', 
            'condition', 'payout', 'profit', 'result', 
            'streak_count', 'streak_type'
        ])
    except Exception as e:
        print(f"❌ Error reading data: {e}")
        return

    # Filter only REAL bets
    df = df[df['mode'].str.contains('REAL', na=False)]
    if len(df) < 100:
        print("⚠️ Not enough real bet data to learn from.")
        return

    print(f"📊 Analyzing {len(df)} real bets...")

    # --- 1. Analyze Isolated Wins (W-W Gaps) ---
    # หาตำแหน่งที่เกิด W-W (ชนะติดกัน 2 ตา)
    ww_mask = (df['result'] == 'WIN') & (df['result'].shift(-1) == 'WIN')
    ww_indices = df.index[ww_mask].tolist()
    
    if len(ww_indices) > 1:
        # คำนวณระยะห่างระหว่างจุดที่เกิด W-W (ลบด้วย 2 เพื่อหาจำนวนตาคั่นกลาง, ถ้าซ้อนทับกัน W-W-W ให้เป็น 0)
        ww_gaps = (pd.Series(ww_indices).diff().dropna() - 2).clip(lower=0)
        
        p95_gap = int(ww_gaps.quantile(0.95))
        max_gap = int(ww_gaps.max())
        optimal_isolated_wins = p95_gap
    else:
        optimal_isolated_wins = 16
        max_gap = 0

    # Safety bounds for isolated wins
    optimal_isolated_wins = max(8, min(optimal_isolated_wins, 24))

    # --- 2. Analyze Loss Streaks (Pandas Vectorized Approach) ---
    # สร้าง Group ID สำหรับชุดข้อมูลที่ติดกัน (ตามเทคนิคที่คุณแนะนำ!)
    streak_groups = (df['result'] != df['result'].shift()).cumsum()
    
    # จัดกลุ่มและนับความยาวของแต่ละสตรีค
    streak_df = df.groupby(streak_groups).agg(
        value=('result', 'first'),
        length=('result', 'size')
    )
    
    # กรองเอาเฉพาะกลุ่มที่เป็น 'LOSS'
    loss_streaks = streak_df[streak_df['value'] == 'LOSS']['length']
    
    if not loss_streaks.empty:
        p95_loss = int(loss_streaks.quantile(0.95))
        optimal_loss_streak = p95_loss
    else:
        optimal_loss_streak = 4

    # Safety bounds for loss streak
    optimal_loss_streak = max(3, min(optimal_loss_streak, 8))

    # --- 3. Save to ai_skills.json (Distill Procedural Skills) ---
    skills = {
        "isolated_wins_threshold": optimal_isolated_wins,
        "loss_streak_threshold": optimal_loss_streak,
        "sawtooth_length": 6 # keep sawtooth static for now
    }
    
    with open(SKILLS_FILE, "w", encoding="utf-8") as f:
        json.dump(skills, f, indent=4)
        
    print(f"✅ Skills updated: Isolated Wins={optimal_isolated_wins}, Loss Streak={optimal_loss_streak}")

    # --- 4. Write to MARKET_MEMORY.md (Build Persistent Facts) ---
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    memory_content = f"""# Stake Market Memory (Hermes AI)

This file stores persistent facts and insights about the current market conditions generated by the Hermes AI Brain.

## Latest Market Status
*   **Timestamp:** {timestamp}
*   **Total Real Bets Analyzed:** {len(df):,}

### 🧠 AI Insights & Procedural Adjustments
*   **W-W Gaps (Isolated Wins):** 
    *   The 95th percentile of W-W gaps is **{optimal_isolated_wins}**.
    *   The absolute worst gap observed is **{max_gap}**.
    *   *Action Taken:* Adjusted `isolated_wins_threshold` to **{optimal_isolated_wins}**.
*   **Loss Streaks:**
    *   The 95th percentile of consecutive losses is **{optimal_loss_streak}**.
    *   *Action Taken:* Adjusted `loss_streak_threshold` to **{optimal_loss_streak}**.

> [!NOTE]
> The bot's parameters have been hot-reloaded dynamically. No restart required.
"""
    with open(MEMORY_FILE, "w", encoding="utf-8") as f:
        f.write(memory_content)
        
    print("📝 MARKET_MEMORY.md updated.")
    print("✨ AI Learning Loop Complete. Bot has been hot-reloaded with new skills!")

if __name__ == "__main__":
    analyze_and_learn()
